version: 0.2

env:
  variables:
    TZ: "Asia/Seoul"
    AWS_DEFAULT_REGION: "ap-northeast-2"
    AWS_ACCOUNT_ID: "226347592148"
    ECR_REPO_NAME: "worldskills-repo"

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com
      - echo "FROM openjdk:17" > Dockerfile
      - echo "WORKDIR /app/" >> Dockerfile
      - echo "COPY ./build/libs/backend-api-0.0.1-SNAPSHOT.jar ." >> Dockerfile
      - echo 'CMD ["java", "-jar", "/app/backend-api-0.0.1-SNAPSHOT.jar"]' >> Dockerfile
      
  build:
    commands:
      - echo Building the Docker image...
      - chmod +x ./gradlew
      - ./gradlew build
      - export IMAGE_TAG=$(TZ=$TZ date +"%H-%M-%S")
      - docker build -t $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$ECR_REPO_NAME:$IMAGE_TAG .
      
  post_build:
    commands:
      - echo Pushing the Docker image to Amazon ECR...
      - docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$ECR_REPO_NAME:$IMAGE_TAG
      - printf '{"ImageURI":"%s"}' $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$ECR_REPO_NAME:$IMAGE_TAG > imageDetail.json

artifacts:
  files:
      - taskdef.json
      - appspec.yml
      - imageDetail.json
